"""Regression tests for one-shot input issues generated by the profile controller."""
from __future__ import annotations

import importlib.util
from pathlib import Path
import unittest

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "collect_issue_command.py"


def load_module():
    if not SCRIPT.is_file():
        return None
    spec = importlib.util.spec_from_file_location("collect_issue_command", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    assert spec and spec.loader
    spec.loader.exec_module(module)
    return module


class IssueCommandTests(unittest.TestCase):
    def setUp(self):
        self.state = {
            "last_comment_id": 5994686763,
            "last_input_issue_number": 0,
        }
        self.event = {
            "action": "opened",
            "issue": {
                "id": 9001,
                "number": 42,
                "title": "runtime/input: left",
                "body": "/left",
                "user": {"login": "octocat"},
            },
        }

    def parser(self):
        module = load_module()
        self.assertIsNotNone(module, "missing scripts/collect_issue_command.py")
        self.assertTrue(callable(getattr(module, "parse_issue_event", None)))
        return module.parse_issue_event

    def test_valid_prefilled_issue_becomes_one_command(self):
        payload = self.parser()(self.event, self.state)
        self.assertEqual(len(payload["commands"]), 1)
        command = payload["commands"][0]
        self.assertEqual(command["command"], "/left")
        self.assertEqual(command["actor"], "octocat")
        self.assertEqual(command["source"], "issue")
        self.assertEqual(command["issue_number"], 42)
        self.assertEqual(payload["max_seen_comment_id"], self.state["last_comment_id"])

    def test_title_and_body_must_agree(self):
        self.event["issue"]["body"] = "/right"
        payload = self.parser()(self.event, self.state)
        self.assertEqual(payload["commands"], [])

    def test_only_six_commands_are_accepted(self):
        self.event["issue"]["title"] = "runtime/input: god"
        self.event["issue"]["body"] = "/god"
        payload = self.parser()(self.event, self.state)
        self.assertEqual(payload["commands"], [])

    def test_replayed_issue_number_is_ignored(self):
        self.state["last_input_issue_number"] = 42
        payload = self.parser()(self.event, self.state)
        self.assertEqual(payload["commands"], [])

    def test_non_opened_event_is_ignored(self):
        self.event["action"] = "edited"
        payload = self.parser()(self.event, self.state)
        self.assertEqual(payload["commands"], [])

    def test_all_profile_controls_parse(self):
        parser = self.parser()
        for slug in ("forward", "back", "left", "right", "fire", "use"):
            with self.subTest(slug=slug):
                event = {
                    **self.event,
                    "issue": {
                        **self.event["issue"],
                        "number": self.event["issue"]["number"] + 1,
                        "title": f"runtime/input: {slug}",
                        "body": f"/{slug}",
                    },
                }
                payload = parser(event, self.state)
                self.assertEqual(payload["commands"][0]["command"], f"/{slug}")


if __name__ == "__main__":
    unittest.main()
