"""Regression tests for one-shot input issues generated by the profile controller."""
from __future__ import annotations

import importlib.util
from pathlib import Path
import unittest

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "collect_issue_command.py"


def load_module():
    if not SCRIPT.is_file():
        return None
    spec = importlib.util.spec_from_file_location("collect_issue_command", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    assert spec and spec.loader
    spec.loader.exec_module(module)
    return module


class IssueCommandTests(unittest.TestCase):
    def setUp(self):
        self.state = {
            "last_comment_id": 5994686763,
            "last_input_issue_number": 0,
        }
        self.event = {
            "action": "opened",
            "issue": {
                "id": 9001,
                "number": 42,
                "title": "runtime/input: left",
                "body": "/left",
                "user": {"login": "octocat"},
            },
        }

    def parser(self):
        module = load_module()
        self.assertIsNotNone(module, "missing scripts/collect_issue_command.py")
        self.assertTrue(callable(getattr(module, "parse_issue_event", None)))
        return module.parse_issue_event

    def test_valid_prefilled_issue_becomes_one_command(self):
        payload = self.parser()(self.event, self.state)
        self.assertEqual(len(payload["commands"]), 1)
        command = payload["commands"][0]
        self.assertEqual(command["command"], "/left")
        self.assertEqual(command["actor"], "octocat")
        self.assertEqual(command["source"], "issue")
        self.assertEqual(command["issue_number"], 42)
        self.assertEqual(payload["max_seen_comment_id"], self.state["last_comment_id"])

    def test_title_and_body_must_agree(self):
        self.event["issue"]["body"] = "/right"
        payload = self.parser()(self.event, self.state)
        self.assertEqual(payload["commands"], [])

    def test_only_six_commands_are_accepted(self):
        self.event["issue"]["title"] = "runtime/input: god"
        self.event["issue"]["body"] = "/god"
        payload = self.parser()(self.event, self.state)
        self.assertEqual(payload["commands"], [])

    def test_replayed_issue_number_is_ignored(self):
        self.state["last_input_issue_number"] = 42
        payload = self.parser()(self.event, self.state)
        self.assertEqual(payload["commands"], [])

    def test_non_opened_event_is_ignored(self):
        self.event["action"] = "edited"
        payload = self.parser()(self.event, self.state)
        self.assertEqual(payload["commands"], [])

    def test_all_profile_controls_parse(self):
        parser = self.parser()
        for slug in ("forward", "back", "left", "right", "fire", "use"):
            with self.subTest(slug=slug):
                event = {
                    **self.event,
                    "issue": {
                        **self.event["issue"],
                        "number": self.event["issue"]["number"] + 1,
                        "title": f"runtime/input: {slug}",
                        "body": f"/{slug}",
                    },
                }
                payload = parser(event, self.state)
                self.assertEqual(payload["commands"][0]["command"], f"/{slug}")

    def test_open_issue_queue_is_sorted_and_filters_invalid_or_old_items(self):
        module = load_module()
        self.assertTrue(callable(getattr(module, "collect_open_issue_commands", None)),
                        "missing collect_open_issue_commands")
        self.state["last_input_issue_number"] = 3
        issues = [
            {"id": 6006, "number": 6, "title": "runtime/input: fire", "body": "/fire",
             "user": {"login": "c"}},
            {"id": 6002, "number": 2, "title": "runtime/input: left", "body": "/left",
             "user": {"login": "old"}},
            {"id": 6005, "number": 5, "title": "runtime/input: right", "body": "/left",
             "user": {"login": "bad"}},
            {"id": 6004, "number": 4, "title": "runtime/input: forward", "body": "/forward",
             "user": {"login": "a"}},
            {"id": 6007, "number": 7, "title": "runtime/input: use", "body": "/use",
             "user": {"login": "pr"}, "pull_request": {"url": "x"}},
        ]
        payload = module.collect_open_issue_commands(issues, self.state)
        self.assertEqual(
            [(x["issue_number"], x["command"], x["actor"]) for x in payload["commands"]],
            [(4, "/forward", "a"), (6, "/fire", "c")],
        )
        self.assertEqual(payload["processed_issue_numbers"], [4, 6])

    def test_open_issue_queue_keeps_comment_cursor_unchanged(self):
        module = load_module()
        self.state["last_comment_id"] = 1234
        issues = [
            {"id": 9002, "number": 9, "title": "runtime/input: back", "body": "/back",
             "user": {"login": "octocat"}},
        ]
        payload = module.collect_open_issue_commands(issues, self.state)
        self.assertEqual(payload["max_seen_comment_id"], 1234)
        self.assertEqual(payload["previous_comment_id"], 1234)


if __name__ == "__main__":
    unittest.main()
